[project]
name = "demo_app"
version = "0.1.0"
description = "None"
readme = "README.md"
authors = [{ name = "Developer" }]
requires-python = ">=3.13"

# Dependencies
dependencies = [
  "fletxr",
  "flet==0.84.0",
  "flet-cli==0.84.0",
  "flet-desktop==0.84.0",
  "flet-web==0.84.0",
]

[tool.uv.sources]
fletxr = { path = "..", editable = true }
